networks:
  dns_net:
    driver: bridge

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    environment:
      TZ: "America/Bogota"
      WEBPASSWORD: "admin"
    volumes:
      - ./pihole/etc-pihole:/etc/pihole
      - ./pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
    cap_add:
      - NET_ADMIN
    restart: always
    networks:
      - dns_net
    dns:
      - 127.0.0.1
      - 1.1.1.1

  wireguard:
    image: weejewel/wg-easy:15
    container_name: wg-easy
    environment:
      WG_HOST: "TU_DNS_O_IP_PUBLICA"
      WG_DEFAULT_DNS: "pihole"
      PASSWORD: "admin123"
      WG_IPV4: "10.8.0.x"
      WG_IPV6: "fd42:42:42::"
    volumes:
      - ./wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"     # interfaz WG-Easy
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    networks:
      - dns_net
    dns:
      - 172.18.0.2    # IP del contenedor Pi-hole en la misma red
